### ISSUE TITLE
SOE when address option data too large

### ISSUE THREAD

**Issue by dmart77** [shevek/dhcp4j#5]
Code to reproduce

```
        RequestedIpAddress addressOption = new RequestedIpAddress();
        addressOption.setData(new byte[]{1,2,3,4,5});
        addressOption.validate();

```

**Comment by cfscosta** [comment]
This is caused by getAddress, it will throw an exception because the address is not correct, to create that exception it will call toString() on this which will call getAddress again... 

#6 <- this should solve the problem.
